# Generated by Django 5.1.3 on 2024-11-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdepo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='type',
        ),
        migrations.AddField(
            model_name='bus',
            name='seating_capacity',
            field=models.IntegerField(null=True),
        ),
    ]
