# Generated by Django 5.1.3 on 2024-11-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busdepo', '0002_remove_bus_type_bus_seating_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
